### ISSUE TITLE
請問如何設定SPI引腳的?就是SDA、SCL、CS、D/C等等，是用庫修改還是默認ESP32 32E 的PIN OUT?

### ISSUE THREAD

**Issue by Cwy0116** [shaoxiongduan/calculator#1]
請問如何設定SPI引腳的?就是SDA、SCL、CS、D/C等等，是用庫修改還是默認ESP32 32E 的PIN OUT?
如何修改?

**Comment by shaoxiongduan** [comment]
直接设定就可以，不用手动设置pinout，详见可以参考u8g2库的4线spi docs
