### ISSUE TITLE
How to install the update for the macropad

### ISSUE THREAD

**Issue by Bow3ryList** [shaoxiongduan/calculator#4]
Hi Shao,

How do I update the SCI-CALC with the fix for the macropad (does is fix the issue with the 7, 8 and 9 keys being swapped with the esc, and the bracket keys)? Is it a case of downloading all the files and putting them onto the SD card using an adaptor or is it just the .bin put the needs to be copied over to the SD in the corresponding folder?

Thanks

Tom

**Comment by shaoxiongduan** [comment]
Hello Tom,

You have to download the main.bin file from my github page (the bin files
are located in the sci-calc-code/bin folder) and replace the main.bin in
the microsd card. Once that's done go to the settings page in the sci-calc,
if there is an update from SD option click that, if not then go to the
programs page, select any game in the bin, and wait for the game to load.
Once the game loads you can press esc to go back (the sci-calc freezes for
a moment here, dont worry). And you should be running the newest code! If
you have any problems or discover any bugs please let me know!

-Shao

**Comment by Bow3ryList** [comment]
Yep, that has fixed the numbers. Thanks

Next question is how do I change the macro customisable keys as I think they are formatted for a different system (maybe for a mac?) . For example, 'copy' launches copilot (windows key +c) on windows 11 and 'paste' launches the clipboard viewer which is 'windows key' and 'v'. Is there a way to edit this?

Thanks in advance for your help

Tom

**Comment by shaoxiongduan** [comment]
Currently you have to modify the code to do so, so follow the vscode + platformio "Setting up dev enviroment" guide in the README. Once the code is set, open up the UIMain.cpp file, and you can modify macros there. Below are some of the name of the keys. So for your case, it's KEY_LEFT_GUI for the windows key.
<img width="927" alt="image" src="https://github.com/user-attachments/assets/c82e2852-214d-47fc-9ede-e1793a42110d">

**Comment by sierrax369** [comment]
Hi Shao
Do you have a timeline when you switch to a "textfile-based" Macro solution? 
Kind Regards

**Comment by Bow3ryList** [comment]
> vscode + platformio

Ah, okay - I thought it needed the 'Arduino IDE' to also be installed to allow the code to be modified. It wasn't clear to me what the 'Arduino IDE' section of setting up the developer environment is required for?

Once the UIMain.cpp has been edited, does it again just replace the file the SD card?

**Comment by shaoxiongduan** [comment]
The Arduino IDE is another option if you want to develop more programs for the sci-calc. Most of the code for the sci-calc are coded with the vscode+platformio configuration.

To update the code, first save the changes you made in the UIMain.cpp file, and then press upload at the bottom:

<img width="522" alt="image" src="https://github.com/user-attachments/assets/22284d5b-895c-4896-8a0f-fc6ad4550ce2">

And also you need to update the main.bin file in the sd card.
First locate the firmware.bin file compiled:
<img width="469" alt="image" src="https://github.com/user-attachments/assets/671f4111-b614-4577-a3e4-f915199bf6af">

Then copy it to the sd-card and rename it to main.bin.
After that, everything should be properly saved and working.

**Comment by Bow3ryList** [comment]
Okay, have follow those steps up to 'upload' but I get the following error message once it completes

![image](https://github.com/user-attachments/assets/04351144-c978-4d1d-9dc0-4521b35bad61)

Is that normal, or have I made a mistake copying the cloning the codes files?

Thanks

**Comment by yangnuozhen** [comment]
> Okay, have follow those steps up to 'upload' but I get the following error message once it completes
> 
> ![image](https://private-user-images.githubusercontent.com/31591202/353125583-04351144-c978-4d1d-9dc0-4521b35bad61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTQ2NjcsIm5iZiI6MTcyMzAxNDM2NywicGF0aCI6Ii8zMTU5MTIwMi8zNTMxMjU1ODMtMDQzNTExNDQtYzk3OC00ZDFkLTlkYzAtNDUyMWIzNWJhZDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA3MDYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMThiNTIzZDgyNTU2NTkzZDA3M2I0NDk1Y2RiYzFiNTFlNWY4ZjI5M2JlYjQ2YjBmOTgzZTVkZDIxMDJjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._d_KXtMgROM9hEvvOP3cabUbqDOTVT6mqS3vcywnQRU)
> 
> Is that normal, or have I made a mistake copying the cloning the codes files?
> 
> Thanks

Hi Tom,

It seems that you did not specify the upload port during the upload process. Please ensure that SCI-CALC is connected to the computer and that the computer can correctly detect and establish a connection with the port.

To check if the port is correctly connected to the computer, you can follow these steps:

### On Windows

1. **Device Manager**:
   - Right-click on the "This PC" or "Computer" icon and select "Manage".
   - In the opened "Computer Management" window, select "Device Manager" on the left side.
   - Expand the "Ports (COM & LPT)" section, where you should see the connected device and its corresponding port number (e.g., COM3, COM4, etc.).

2. **CMD**:
   - Open Command Prompt (press `Win + R`, type `cmd`, and then press Enter).
   - Enter the following command to view the currently connected serial ports:

     ```cmd
     mode
     ```

### On macOS

1. **Terminal**:
   - Open Terminal (you can find it in "Applications" -> "Utilities").
   - Enter the following command to view the currently connected serial ports:

     ```bash
     ls /dev/tty.*
     ```

   - You should see devices like `/dev/tty.usbserial-xxxx` or `/dev/tty.usbmodemxxxx`.

### On Linux

1. **Terminal**:
   - Open Terminal.
   - Enter the following command to view the currently connected serial ports:

     ```bash
     dmesg | grep tty
     ```

   - You should see devices like `/dev/ttyUSB0` or `/dev/ttyACM0`.

### Using PlatformIO to Check Ports

If you want to check whether the device is correctly recognized by PlatformIO, you can use the following command to list all ports readable by PlatformIO:

```bash
pio device list
```

This will display all currently connected serial devices and their detailed information.

After ensuring the correct connection, try uploading again.

Hope this helps!

**Comment by Bow3ryList** [comment]
Thanks for bearing with us on that one Shao - just got around to trying that and it appears to have done the trick and allowed me to edit the marcopad functions so that they are compatible with Windows :)
